version: '3.7'

services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      # PUID is the user ID that the Transmission container will run as.
      # Setting PUID to 1000 is a common practice to match the default user ID of the first user created on a Unix-like system.
      # This helps to avoid permission issues when accessing files created by the container.
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Bangkok
      - TRANSMISSION_WEB_HOME=/combustion-release/ # optional
      - USER=your-username # optional
      - PASS=your-password # optional
    volumes:
      - transmission-config:/config
      - transmission-downloads:/downloads
    ports:
      - 9091:9091 # UI port
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

volumes:
  transmission-config:
    driver: local
  transmission-downloads:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=20G" # Limit disk size to 20GB