apiVersion: 1
groups:
  - name: InstanceDownGroup
    folder: General
    interval: 1m
    rules:
      - uid: instance_down
        title: InstanceDown
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              expr: up == 0
              interval: ""
              intervalFactor: 2
              legendFormat: ""
              refId: A
        execErrState: Alerting
        for: 5m
        noDataState: NoData
        notifications: []